// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-0mu-DVuk6f_JVeWqK_RTgW9bKNbIX5w',
    appId: '1:659390055460:web:1ccea07521ab15623284b1',
    messagingSenderId: '659390055460',
    projectId: 'test-bug-834cb',
    authDomain: 'test-bug-834cb.firebaseapp.com',
    storageBucket: 'test-bug-834cb.firebasestorage.app',
    measurementId: 'G-DY2X8F3LTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVIocW-oR5yTRwrGSY9C7d2Oio40UiiOc',
    appId: '1:659390055460:android:b9450b894930e1e63284b1',
    messagingSenderId: '659390055460',
    projectId: 'test-bug-834cb',
    storageBucket: 'test-bug-834cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApSrfKhPYBT6MeWY-OFG8435hqnF7v5Ko',
    appId: '1:659390055460:ios:86c26d564b4f928f3284b1',
    messagingSenderId: '659390055460',
    projectId: 'test-bug-834cb',
    storageBucket: 'test-bug-834cb.firebasestorage.app',
    iosBundleId: 'com.example.flutterCi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApSrfKhPYBT6MeWY-OFG8435hqnF7v5Ko',
    appId: '1:659390055460:ios:86c26d564b4f928f3284b1',
    messagingSenderId: '659390055460',
    projectId: 'test-bug-834cb',
    storageBucket: 'test-bug-834cb.firebasestorage.app',
    iosBundleId: 'com.example.flutterCi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-0mu-DVuk6f_JVeWqK_RTgW9bKNbIX5w',
    appId: '1:659390055460:web:3844a1511eef4b853284b1',
    messagingSenderId: '659390055460',
    projectId: 'test-bug-834cb',
    authDomain: 'test-bug-834cb.firebaseapp.com',
    storageBucket: 'test-bug-834cb.firebasestorage.app',
    measurementId: 'G-F0RVBMBVQV',
  );
}
